name: coffe_splash_screen
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  lottie: ^1.4.3

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/images/coffeepic.png
    - assets/animated_coffee.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
